helmController:
  create: true
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}

imageAutomationController:
  create: true
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}

imageReflectionController:
  create: true
  container:
    additionalargs:
    - --aws-autologin-for-ecr
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}

kustomizeController:
  create: true
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}

notificationController:
  create: true
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}

sourceController:
  create: true
  affinity: ${node_affinity}
  nodeSelector: ${node_selector}